#!/bin/bash

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
  echo "You can't commit directly to branch \"master\". Please use a feature branch!"
  exit 1
fi

if [ "$branch" = "develop" ]; then
  echo "You can't commit directly to branch \"develop\". Please use a feature branch!"
  exit 1
fi
